default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite

ci:
  autoupdate_schedule: monthly
  skip: ["cargo-fmt"]

# cf https://pre-commit.com/#regular-expressions
exclude: |
  (?x)^(
      tests/templates/invalid.txt|
      scripts/django_tests_use_rusty_templates.patch
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 0671d8ab202c4ac093b78433ae5baf74f3fc7246  # frozen: v0.15.15
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/AndrejOrsula/pre-commit-cargo
    rev: 33ae92ed9b1a4392c8ac5fdef46887640d866e1e  # frozen: 0.5.0
    hooks:
      - id: cargo-fmt
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 254dd0011fda0cd4bbb281ff135792b157e43e1f  # frozen: 0.11.17
    hooks:
      - id: uv-lock
      - id: uv-sync
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: 9257c6050c0261b8c57e712f632dc4a8010109a9  # frozen: v1.25.2
    hooks:
      - id: zizmor
  - repo: https://github.com/crate-ci/typos
    rev: 0758ccd3261dc7b0594e9b698113eb08d3ba25b5  # frozen: v1
    hooks:
      - id: typos
